//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCScanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCScanner.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC Files(*.nc) | *.nc.
        /// </summary>
        internal static string BrowseForNCFilter {
            get {
                return ResourceManager.GetString("BrowseForNCFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an NC File.
        /// </summary>
        internal static string BrowseForNCTitle {
            get {
                return ResourceManager.GetString("BrowseForNCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?:X)(?&lt;XPos&gt;(\+|-)?(\d+\.?\d*|\.\d+))|(?:Y)(?&lt;YPos&gt;(\+|-)?(\d+\.?\d*|\.\d+))|(?:Z)(?&lt;ZPos&gt;(\+|-)?(\d+\.?\d*|\.\d+)).
        /// </summary>
        internal static string PositionRegex {
            get {
                return ResourceManager.GetString("PositionRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xlsx File(*.xlsx) | *.xlsx.
        /// </summary>
        internal static string SaveReportFilter {
            get {
                return ResourceManager.GetString("SaveReportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report As....
        /// </summary>
        internal static string SaveReportTitle {
            get {
                return ResourceManager.GetString("SaveReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (M0?6)?(T0?\d*.?\d+)(M0?6)?((?:.*)(\(.*\)))?.
        /// </summary>
        internal static string ToolRegex {
            get {
                return ResourceManager.GetString("ToolRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (G54\.1\s*P\d|G5[4-9](?!\.)).
        /// </summary>
        internal static string WorkOffsetRegex {
            get {
                return ResourceManager.GetString("WorkOffsetRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPos.
        /// </summary>
        internal static string XPositionGroup {
            get {
                return ResourceManager.GetString("XPositionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YPos.
        /// </summary>
        internal static string YPositionGroup {
            get {
                return ResourceManager.GetString("YPositionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZPos.
        /// </summary>
        internal static string ZPositionGroup {
            get {
                return ResourceManager.GetString("ZPositionGroup", resourceCulture);
            }
        }
    }
}
